spring:
  boot:
    admin:
      url: http://192.168.1.33:13307/adminServer,http://192.168.1.34:13307/adminServer
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.33:13303/eurekaServer/eureka/,http://192.168.1.34:13303/eurekaServer/eureka/
