config:
  message: Greetings from the PARTICIPANT microservice [using the PRODUCTION config]

spring:
  data:
    mongodb:
      database: activitiesDB
      host: 192.168.1.32
      port: 27017
      events: participantEvents
      snapshots: participantSnapshots

server:
  port: 13305

management:
  port: 13306
  context-path: /manage
