config:
  message: Greetings from the EUREKA server microservice [using the BASE config]

spring:
  boot:
    admin:
      client:
        health-url: http://${eureka.instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${eureka.instance.hostname}:${management.port}${management.context-path}
        service-url: http://${eureka.instance.hostname}:${server.port}${server.context-path}
        
server:
  port: 13303
  context-path: /eurekaServer

management:
  port: 13304
  context-path: ${server.context-path}/manage

error:
  whitelabel:
    enabled: false

eureka:
  # defaultZone.context-path is a made up eureka property for reuse
  defaultZone:
    context-path: eureka
  dashboard:
    path: dashboard
  instance:
    preferIpAddress: true
    homePageUrl: https://${eureka.instance.hostname}:${server.port}${server.context-path}/
    statusPageUrl: http://${eureka.instance.hostname}:${management.port}${management.context-path}/info
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${management.port}${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.context-path}/${eureka.defaultZone.context-path}/
  server:
    enable-self-preservation: false
