config:
  message: Greetings from the ADMIN SERVER microservice [using the BASE config]

spring:
  boot:
    admin:
      client:
        health-url: http://${instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${instance.hostname}:${management.port}${management.context-path}
        service-url: http://${instance.hostname}:${server.port}${server.context-path}
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,hystrix.stream,turbine.stream,activiti

server:
  port: 13307
  context-path: /adminServer
  error:
    whitelabel:
      enabled: false
      
management:
  port: 13308
  context-path: ${server.context-path}/manage

zuul:
  sensitive-headers: # Deliberately blank so clients with basic authentication can authenticate

