config:
  message: Greetings from the ADMIN SERVER microservice [using the BASE config]

spring:
  boot:
    admin:
      context-path: /adminServer
      client:
        health-url: http://${instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${instance.hostname}:${management.port}${management.context-path}
        service-url: http://${instance.hostname}:${server.port}${server.context-path}

server:
  port: 13307

management:
  port: 13308
  context-path: ${spring.boot.admin.context-path}/manage

error:
  whitelabel:
    enabled: false

