config:
  message: Greetings from the ADMIN SERVER microservice [using the LOCAL config]
     
spring:
  boot:
    admin:
      url: http://localhost:13307/adminServer
       
instance:
  hostname: localhost