config:
  message: Greetings from the FACILITATED ACTIVITY microservice [using the BASE config]

spring:
  autoconfigure: # exclude in mem db
    exclude[0]: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    exclude[1]: org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    exclude[2]: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  boot:
    admin:
      client:
        health-url: http://${instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${instance.hostname}:${management.port}${management.context-path}
        service-url: http://${instance.hostname}:${server.port}${server.context-path}
  cache:
    jcache:
      config: ehcache.xml
  data:
    cassandra:
      keyspace-name: facilitated_activity
    mongodb:
      database: activitiesDB
      port: 27017
      events: facilitatedActivityEvents
      snapshots: facilitatedActivitySnapshots
      
server:
  port: 13309
  context-path: /activity/facilitated

management:
  port: 13310
  context-path: ${server.context-path}/manage

error:
  whitelabel:
    enabled: false
  
eureka:
  instance:
    preferIpAddress: true
    homePageUrl: https://${instance.hostname}:${server.port}${server.context-path}/
    statusPageUrl: http://${instance.hostname}:${management.port}${management.context-path}/info
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrl: http://${instance.hostname}:${management.port}${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health

