config:
  message: Greetings from the PARTICIPANT microservice [using the LOCAL config]

spring:
  data:
    mongodb:
      host: 192.168.1.32
      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:13303/eurekaServer/eureka/