config:
  message: Greetings from the PARTICIPANT microservice [using the LOCAL config]

eureka:
  instance:
    hostname: localhost
    
spring:
  boot:
    admin:
      url: http://localhost:13307/adminServer
  data:
    cassandra:
      contact-points: 192.168.1.32
    mongodb:
      host: 192.168.1.32