config:
  message: Greetings from the PARTICIPANT microservice [using the BASE config]

spring:
  autoconfigure: # exclude in mem db
    exclude[0]: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    exclude[1]: org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
    exclude[2]: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  boot:
    admin:
      client:
        health-url: http://${eureka.instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${eureka.instance.hostname}:${management.port}${management.context-path}
        service-url: http://${eureka.instance.hostname}:${server.port}${server.context-path}
  data:
    cassandra:
      keyspace-name: participant
    mongodb:
      database: activitiesDB
      port: 27017
      events: participantEvents
      snapshots: participantSnapshots
      
server:
  port: 13305
  context-path: /participant

management:
  port: 13306
  context-path: ${server.context-path}/manage

error:
  whitelabel:
    enabled: false
  
eureka:
  instance:
    preferIpAddress: true
    homePageUrl: https://${eureka.instance.hostname}:${server.port}${server.context-path}/
    statusPageUrl: http://${eureka.instance.hostname}:${management.port}${management.context-path}/info
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${management.port}${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health

