config:
  message: Greetings from the ACTIVITIES UI microservice [using the BASE config]

spring:
  boot:
    admin:
      auto-deregistration: true
      client:
        health-url: http://${instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${instance.hostname}:${management.port}${management.context-path}
        service-url: http://${instance.hostname}:${server.port}${server.context-path}
  cache:
    jcache:
      config: ehcache.xml
      
server:
  port: 13309
  context-path: /activities/ui

management:
  port: 13310
  context-path: ${server.context-path}/manage

error:
  whitelabel:
    enabled: false

external:
  participant:
    url: http://participant-microservice/participant

hystrix:
  command:
    participantsByCriteria:
      execution.isolation.thread.timeoutInMilliseconds: 10000
              
eureka:
  instance:
    preferIpAddress: true
    homePageUrl: https://${instance.hostname}:${server.port}${server.context-path}/
    statusPageUrl: http://${instance.hostname}:${management.port}${management.context-path}/info
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrl: http://${instance.hostname}:${management.port}${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
    metadata-map:
      management:
        port: ${management.port} # This is needed by Netflix turbine

