config:
  message: Greetings from the ACTIVITIES UI microservice [using the BASE config]

spring:
  boot:
    admin:
      auto-deregistration: true
      client:
        health-url: http://${instance.hostname}:${management.port}${management.context-path}/health
        management-url: http://${instance.hostname}:${management.port}${management.context-path}
        service-url: http://${instance.hostname}:${server.port}${server.context-path}
  cache:
    jcache:
      config: ehcache.xml
      
server:
  port: 13309
  context-path: /activities/ui
  session:
    timeout: 600 # 10 minutes
  error:
    whitelabel:
      enabled: false

management:
  port: 13310
  context-path: ${server.context-path}/manage
      
vaadin:
  servlet:
    close-idle-sessions: true # Don't want Vaadin's heart beat signal to keep the session alive
    heartbeat-interval: 300 # The session timeout should be a multiple of the heartbeat interval

togglz:
  console:
    enabled: true
    path: /togglz-console
    feature-admin-authority: ROLE_ADMIN

external:
  participant:
    url: http://participant-microservice/participant

hystrix:
  command:
    participantsByCriteria:
      execution.isolation.thread.timeoutInMilliseconds: 10000
              
eureka:
  instance:
    preferIpAddress: true
    homePageUrl: https://${instance.hostname}:${server.port}${server.context-path}/
    statusPageUrl: http://${instance.hostname}:${management.port}${management.context-path}/info
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrl: http://${instance.hostname}:${management.port}${management.context-path}/health
    healthCheckUrlPath: ${management.context-path}/health
    metadata-map:
      management:
        port: ${management.port} # This is needed by Netflix turbine

